"""VQE_qibo.py
================================================================================
Circuit-level safeguard for the real Hopf ansatz gradient formula.

This script is separate from the layerwise numerical panel. It uses Qibo to
build explicit ancilla circuits for transition-moment estimation. For each
Hopf coordinate i and Pauli term P_alpha, it prepares a coherent superposition
of the current Hopf state and the normalized tangent state, applies a controlled
Pauli operation, and estimates the real transition moment

    Re <partial_i psi(theta)| P_alpha |psi(theta)>.

The tangent state is generated by hopf_utils.theta_hopf_tangent_state, using the
same Hopf circuit skeleton as the forward ansatz. The resulting sampled
Hadamard-test gradient is compared against the exact state-vector gradient in a
small TFIM VQE run.

This file is a circuit-realizability check. The main paper plots use the
layerwise signed-branch estimators in VQE_Layerwise_ADAM_EGTCG.py and
MET_Layerwise_ADAM_EGTCG.py.

Output:
    * VQE_ADAM_MC_qibo.pdf.
    * Console logs comparing exact-gradient and circuit-sampled trajectories.

Dependencies: numpy, matplotlib, qibo, hopf_utils.
================================================================================
"""

import math
import numpy as np
import matplotlib.pyplot as plt
from qibo import models, gates
from hopf_utils import (
    qibo_circuit, gates_order, canonical_initial_state, 
    theta_from_vector, clip_theta_hopf_real, 
    theta_hopf_tangent_state, partial_derivative_column_real,
    vector_from_theta
)

def init_theta_from_canonical_state(n: int, seed: int = 123):
    psi0 = canonical_initial_state(n, seed)
    # Using 'real' case for theta_from_vector
    theta0 = clip_theta_hopf_real(theta_from_vector(psi0, 'real'), n=n)
    return theta0

# ---------------------------
# TFIM Hamiltonian (n-qubit, open boundary)
# ---------------------------

def kron_n(ops):
    out = ops[0]
    for m in ops[1:]:
        out = np.kron(out, m)
    return out

def tfim_hamiltonian(n=6, J=1.0, h=0.6):
    I = np.eye(2)
    X = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=float)
    Z = np.array([[1.0, 0.0], [0.0,-1.0]], dtype=float)
    H = np.zeros((1 << n, 1 << n), dtype=float)
    for i in range(n - 1):
        ops = [I] * n
        ops[i], ops[i + 1] = Z, Z
        H -= J * kron_n(ops)
    for i in range(n):
        ops = [I] * n
        ops[i] = X
        H -= h * kron_n(ops)
    return H

def decompose_H_terms(n=6, J=1.0, h=0.6):
    terms = []
    for i in range(n - 1):
        terms.append((-J, ('ZZ', i, i+1)))
    for i in range(n):
        terms.append((-h, ('X', i)))
    return terms

def pauli_string_matrix(term, n):
    I = np.eye(2)
    X = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=float)
    Z = np.array([[1.0, 0.0], [0.0,-1.0]], dtype=float)
    ops = [I] * n
    kind = term[0]
    if kind == 'X':
        i = term[1]
        ops[i] = X
    elif kind == 'Z':
        i = term[1]
        ops[i] = Z
    elif kind == 'ZZ':
        i, j = term[1], term[2]
        ops[i] = Z
        ops[j] = Z
    else:
        raise ValueError(f"Unsupported term label: {term}")
    return kron_n(ops)

def build_decomposition(n=6, J=1.0, h=0.6):
    labeled = decompose_H_terms(n, J, h)
    coeffs = np.array([float(c) for c, _ in labeled], dtype=float)
    labels = [t for _, t in labeled]
    Pmats  = [pauli_string_matrix(t, n) for t in labels]
    return coeffs, labels, Pmats


# ---------------------------
# Hadamard-test transition-moment circuit construction in Qibo
# ---------------------------


# ---------------------------
# Hopf ansatz blocks (Qibo)
# ---------------------------

def _mask_bitpos(mask: int) -> int:
    """Return bit position (0=LSB) of a power-of-two mask."""
    if mask <= 0 or (mask & (mask - 1)) != 0:
        raise ValueError(f"Expected power-of-two mask, got {mask}.")
    return (mask.bit_length() - 1)

def _bitpos_to_qubit(bitpos: int, n: int) -> int:
    """Map bit position (0=LSB) to Qibo qubit index (0=MSB) for an n-qubit register."""
    return (n - 1 - bitpos)

def _mask_to_qubits(mask: int, n: int):
    """Convert an integer mask to a sorted list of Qibo qubit indices (ascending)."""
    qubits = []
    for bp in range(n):
        if (mask >> bp) & 1:
            qubits.append(_bitpos_to_qubit(bp, n))
    return sorted(qubits)

def add_hopf_block_with_ancilla(circ, n, thetas, case='real', anc=0, branch='anti'):
    """Add a Hopf ansatz block on the system register, coherently controlled by an ancilla.

    Register layout in this script:
        ancilla is qubit `anc` (typically 0),
        system qubits are [1, ..., n] (n-qubit Hopf ansatz).

    Control conventions:
        - branch='control': apply the Hopf ansatz block when ancilla is |1>
        - branch='anti'   : apply the Hopf ansatz block when ancilla is |0> (implemented by X on ancilla)
    """
    assert case == 'real', "This script currently targets the real Hopf case only."

    ctrl, anti_latex, targ, index = gates_order(n, case)

    if branch == 'anti':
        circ.add(gates.X(anc))

    # Iterate gate-by-gate in the Hopf schedule
    for ctrl_mask, _anti_mask_latex, targ_mask, idx in zip(ctrl, anti_latex, targ, index):
        # target qubit (system register)
        t_bitpos = _mask_bitpos(targ_mask)
        t_qubit_sys = _bitpos_to_qubit(t_bitpos, n)  # 0..n-1 within system
        t_qubit = 1 + t_qubit_sys  # shift by 1 because ancilla is at 0

        # Prefix bits (more significant than target bitpos) determine the selector controls.
        prefix_bitpos = list(range(t_bitpos + 1, n))
        prefix_mask = sum((1 << bp) for bp in prefix_bitpos)

        # Physical anti-controls are prefix bits that must be 0 (i.e., prefix minus ctrl_mask).
        physical_anticontrol_mask = (prefix_mask & (~ctrl_mask)) & ((1 << n) - 1)

        controls_sys = _mask_to_qubits(prefix_mask, n)
        anticontrols_sys = _mask_to_qubits(physical_anticontrol_mask, n)

        # Shift system indices by +1 and add ancilla as a positive control
        controls_all = [anc] + [1 + q for q in controls_sys]

        # Implement anti-controls by X-conjugation on system qubits that must be 0
        for q in anticontrols_sys:
            circ.add(gates.X(1 + q))

        theta = thetas[int(idx) - 1]  # idx is 1-based for the real case
        circ.add(gates.RY(t_qubit, 2 * theta).controlled_by(*controls_all))

        for q in anticontrols_sys:
            circ.add(gates.X(1 + q))

    if branch == 'anti':
        circ.add(gates.X(anc))

def controlled_pauli_layer(circ, anc, term):
    """Apply controlled-Pα with ancilla as control."""
    kind = term[0]
    if kind == 'X':
        i = term[1]
        circ.add(gates.CNOT(anc, 1 + i))
    elif kind == 'Z':
        i = term[1]
        circ.add(gates.CZ(anc, 1 + i))
    elif kind == 'ZZ':
        i, j = term[1], term[2]
        circ.add(gates.CZ(anc, 1 + i))
        circ.add(gates.CZ(anc, 1 + j))
    else:
        raise ValueError(f"Unsupported Pauli term: {term}")


def hadamard_test_sigma_x(theta, theta_i, term, Ns):
    """
    Build ancilla+system circuit for a single (i, α) pair and estimate ⟨σ_x⟩ on ancilla.
    """
    n = int(round(math.log2(len(theta) + 1)))
    circ = models.Circuit(1 + n)
    circ.add(gates.H(0))
    # anti-controlled U_theta on ancilla=|0>
    add_hopf_block_with_ancilla(circ, n, theta, case='real', anc=0, branch='anti')
    # controlled U_{theta^(i)} on ancilla=|1>
    add_hopf_block_with_ancilla(circ, n, theta_i, case='real', anc=0, branch='control')
    # controlled Pauli
    controlled_pauli_layer(circ, 0, term)
    # measure σ_x
    circ.add(gates.H(0))
    circ.add(gates.M(0))
    res = circ(nshots=Ns)
    samples = res.samples()
    a_bits = samples[:, 0]
    p0 = float(np.count_nonzero(a_bits == 0)) / Ns
    exp_x = 2 * p0 - 1
    return exp_x

# ---------------------------
# Energies & Gradients
# ---------------------------

def energy(theta, H):
    # Using analytic reconstruction for speed in this test
    psi = vector_from_theta(theta, 'real')
    return float(psi @ (H @ psi))

def grad_theta_ideal(theta, H):
    """Exact gradient via unnormalized derivative columns."""
    psi = vector_from_theta(theta, 'real')
    Hpsi = H @ psi
    L = len(theta)
    g = np.zeros(L)
    for i in range(1, L + 1):
        dpi = partial_derivative_column_real(theta, i)
        g[i - 1] = 2.0 * float(dpi @ Hpsi)
    return g

def grad_theta_sampling(theta, c_term_pairs, Ns=1000):
    """
    Hadamard-test transition-moment gradient:
      for each i and Pauli term P_alpha, build the ancilla+system circuit
      and measure <sigma_x> to estimate Re <partial_i psi|P_alpha|psi>.
    """
    n = int(round(math.log2(len(theta) + 1)))
    L = (1 << n) - 1
    g = np.zeros(L, dtype=float)
    for i in range(1, L + 1):
        # Synthesized tangent-state parameters from hopf_utils.
        theta_i = theta_hopf_tangent_state(theta, i, 'real')
        
        acc = 0.0
        for c, term in c_term_pairs:
            exp_x = hadamard_test_sigma_x(theta, theta_i, term, Ns=Ns)
            acc += c * exp_x
            
        # Analytic metric factor sqrt(g_ii).
        dpi = partial_derivative_column_real(theta, i)
        gi_sqrt = float(np.linalg.norm(dpi))
        g[i - 1] = 0.0 if gi_sqrt < 1e-15 else (2.0 * gi_sqrt * acc)
    return g

# ---------------------------
# Adam optimizer
# ---------------------------

class Adam:
    def __init__(self, dim, lr=0.02, beta1=0.9, beta2=0.999, eps=1e-8):
        self.lr = lr
        self.b1, self.b2, self.eps = beta1, beta2, eps
        self.m = np.zeros(dim)
        self.v = np.zeros(dim)
        self.t = 0
    def step(self, x, g):
        self.t += 1
        self.m = self.b1 * self.m + (1 - self.b1) * g
        self.v = self.b2 * self.v + (1 - self.b2) * (g * g)
        m_hat = self.m / (1 - self.b1 ** self.t)
        v_hat = self.v / (1 - self.b2 ** self.t)
        return x - self.lr * (m_hat / (np.sqrt(v_hat) + self.eps))

# ---------------------------
# VQE loop
# ---------------------------

def vqe_run_dual(n=6, steps=50, lr=0.02, Ns=1000, seed=123):
    H = tfim_hamiltonian(n=n, J=1.0, h=0.6)
    evals, _ = np.linalg.eigh(H)
    exact_E = float(np.min(evals))

    coeffs, labels, Pmats = build_decomposition(n=n, J=1.0, h=0.6)
    c_term_pairs = list(zip(coeffs.tolist(), labels))

    L = (1 << n) - 1
    # rng = np.random.default_rng(seed)
    psi0 = canonical_initial_state(n, seed)
    theta0 = theta_from_vector(psi0, 'real')
    theta0 = clip_theta_hopf_real(theta0, n=n)
    
    theta_ideal    = theta0.copy()
    theta_honest   = theta0.copy()
    opt_ideal    = Adam(dim=L, lr=lr)
    opt_honest   = Adam(dim=L, lr=lr)

    energies_ideal = []
    energies_honest  = []

    num_params = L
    num_terms = len(labels)
    total_preparations = num_params * num_terms * Ns
    print(f"[Hadamard test] total ancilla shots per iteration: {total_preparations}")

    for t in range(steps):
        E_ideal  = energy(theta_ideal, H)
        E_honest = energy(theta_honest, H)
        energies_ideal.append(E_ideal)
        energies_honest.append(E_honest)

        g_id  = grad_theta_ideal(theta_ideal, H)
        g_ht  = grad_theta_sampling(theta_honest, c_term_pairs, Ns=Ns)

        theta_ideal  = opt_ideal.step(theta_ideal, g_id)
        theta_honest = opt_honest.step(theta_honest, g_ht)

        tiny = 1e-9
        theta_ideal  = np.clip(theta_ideal,  tiny, (math.pi/2) - tiny)
        theta_honest = np.clip(theta_honest, tiny, (math.pi/2) - tiny)
        
        if t % 10 == 0:
            print(f"Iter {t}: E_exact={E_ideal:.4f}, E_MC={E_honest:.4f}")

    energies_ideal.append(energy(theta_ideal, H))
    energies_honest.append(energy(theta_honest, H))
    return np.array(energies_ideal), np.array(energies_honest), exact_E

if __name__ == "__main__":
    n = 4
    steps = 100
    lr = 0.02
    Ns = 10 

    E_ideal, E_honest, E_exact = vqe_run_dual(n=n, steps=steps, lr=lr, Ns=Ns, seed=38)

    plt.figure()
    x = np.arange(len(E_ideal))
    plt.plot(x, E_ideal,  label="VQE (exact gradient)", linewidth=2.0)
    plt.plot(x, E_honest, label=f"VQE (Hadamard MC: Ns={Ns})", color="green",linestyle="--", linewidth=2.0)
    plt.axhline(E_exact, linestyle="--", color="gray", label="Exact ground energy")
    plt.xlabel("Iteration")
    plt.ylabel("Energy")
    plt.title("VQE with Real Hopf Ansatz (Qibo)")
    plt.legend()
    plt.tight_layout()
    plt.savefig("VQE_ADAM_MC_qibo.pdf", dpi=200)
    plt.show()
